// Node.js script to build a list of requires necessary for webpack to
// statically require things from the set of formats/ directories.
var _ = require('lodash');
var fs = require('fs');

function getTypesFromDir(path, parentString) {
  parentString = parentString || '';

  // make sure this is a folder:
  if (!fs.lstatSync(path).isDirectory()) {
    return {}; // if this is just a file, ignore it
  }

  // Get the list of files/folders in this folder
  var dir_contents = fs.readdirSync(path);
  
  // Figure out if this is a bottom-level directory (i.e. has a schema):
  if (_.includes(dir_contents, 'schema.js')) {
    // Get the list of all examples from 'examples/' folder
    var examples_list = fs.readdirSync(path+'/examples');
    // Build up an object for this media type with examples and schema:
    var type = {
      schema: 'require("'+path+'/schema.js'+'")',
      examples: _.reduce(examples_list, function(acc, ex) {
        acc[ex] = 'require("'+path+'/examples/'+ex+'")'
        return acc;
      }, {}),
    };
    // Return an object that contains this media type info at the proper key:
    var ret = {};
    ret[parentString] = type;
    return ret;
  }

  // Otherwise, loop through all files in this folder and look for types in them:
  return _.reduce(dir_contents, function(acc, l) {
    // Normally, type strings are built with 'dots' between names
    var combiner = '.';
    // But if it's the +json on the end, no combining string is needed (the '+' is the combiner)
    if (l.startsWith('+')) combiner = '';
    // And the first one (application) should end with a '/'
    if (parentString === 'application') combiner = '/';
    if (parentString === '') combiner = '';
    return _.merge(acc, getTypesFromDir(path+'/'+l, parentString + combiner + l));
  }, {});
}
var types = getTypesFromDir('../formats');

var str = '// WARNING: this file is auto-generated by buildRequiresFromDirs.  Don\'t change it.\n';
str += 'module.exports = {\n';
_.each(_.keys(types), function(type_key) {
  var t = types[type_key];
  str += '  "'+type_key+'": {\n';
  str += '    schema: ' + t.schema + ',\n', // require('../formats/application/vnd/oada/bookmarks/1/+json/schema.js')
  str += '    examples: {\n';
  _.each(_.keys(t.examples), function(e) {
    str += '      "' + e + '": ' + t.examples[e] + ',\n';
  });
  str += '    },\n';
  str += '  },\n';
});
str += '};';
fs.writeFileSync('types.js', str);
console.log('types.js written successfully');


